language: php
sudo: false

php: 7.2
php: 7.3

install:
  - composer update --prefer-stable --prefer-dist

script:
    - composer test-ci

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml

