language: php
sudo: false

php: 7.0

addons:
    apt_packages:
        - libgeoip-dev

install:
  - pecl install geoip-1.1.1
  - composer update --prefer-stable --prefer-dist

script:
    - composer test

