language: php

php: 7.2

addons:
    apt_packages:
        - libgeoip-dev

install:
    - pecl install geoip-1.1.1
    - composer update --prefer-stable --prefer-dist

script:
    - composer test-ci

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml
